#pragma once
#include "onnxruntime_c_api.h"

// The Clang importer skips typedefs to INCOMPLETE structs, so every opaque
// ORT runtime class is completed here with a dummy member. The library
// hands out the real objects; these definitions only give the Swift
// importer something to hang the type on — never dereferenced or
// allocated from Swift. (Completing a previously-incomplete struct is
// legal C; types that already have a real definition are skipped.)
#define ORT_SWIFT_COMPLETE(X) struct Ort##X { unsigned char _swift_opaque_do_not_use; };
ORT_SWIFT_COMPLETE(ArenaCfg)
ORT_SWIFT_COMPLETE(CANNProviderOptions)
ORT_SWIFT_COMPLETE(CUDAProviderOptionsV2)
ORT_SWIFT_COMPLETE(CustomOpDomain)
ORT_SWIFT_COMPLETE(DeviceEpIncompatibilityDetails)
ORT_SWIFT_COMPLETE(DnnlProviderOptions)
ORT_SWIFT_COMPLETE(Env)
ORT_SWIFT_COMPLETE(EpAssignedNode)
ORT_SWIFT_COMPLETE(EpAssignedSubgraph)
ORT_SWIFT_COMPLETE(EpDevice)
ORT_SWIFT_COMPLETE(ExternalInitializerInfo)
ORT_SWIFT_COMPLETE(ExternalResourceImporter)
ORT_SWIFT_COMPLETE(Graph)
ORT_SWIFT_COMPLETE(HardwareDevice)
ORT_SWIFT_COMPLETE(IoBinding)
ORT_SWIFT_COMPLETE(KeyValuePairs)
ORT_SWIFT_COMPLETE(Logger)
ORT_SWIFT_COMPLETE(LoraAdapter)
ORT_SWIFT_COMPLETE(MapTypeInfo)
ORT_SWIFT_COMPLETE(MemoryInfo)
ORT_SWIFT_COMPLETE(Model)
ORT_SWIFT_COMPLETE(ModelCompilationOptions)
ORT_SWIFT_COMPLETE(ModelMetadata)
ORT_SWIFT_COMPLETE(Node)
ORT_SWIFT_COMPLETE(NvTensorRtRtxProviderOptions)
ORT_SWIFT_COMPLETE(Op)
ORT_SWIFT_COMPLETE(OpAttr)
ORT_SWIFT_COMPLETE(OptionalTypeInfo)
ORT_SWIFT_COMPLETE(PrepackedWeightsContainer)
ORT_SWIFT_COMPLETE(RunOptions)
ORT_SWIFT_COMPLETE(SequenceTypeInfo)
ORT_SWIFT_COMPLETE(Session)
ORT_SWIFT_COMPLETE(SessionOptions)
ORT_SWIFT_COMPLETE(ShapeInferContext)
ORT_SWIFT_COMPLETE(Status)
ORT_SWIFT_COMPLETE(SyncStream)
ORT_SWIFT_COMPLETE(TensorRTProviderOptionsV2)
ORT_SWIFT_COMPLETE(TensorTypeAndShapeInfo)
ORT_SWIFT_COMPLETE(ThreadingOptions)
ORT_SWIFT_COMPLETE(ThreadPoolParams)
ORT_SWIFT_COMPLETE(TypeInfo)
ORT_SWIFT_COMPLETE(Value)
ORT_SWIFT_COMPLETE(ValueInfo)
ORT_SWIFT_COMPLETE(X)
